version: "3.9"
services:
  postgres:
    image: "postgres:12.4"
    container_name: "mesrecettesdb"
    environment:
      POSTGRES_DB: mesrecettesdb
      POSTGRES_PASSWORD: pwd
    ports:
      - "54320:5432"
