package fr.deroffal.mesrecettesback.adapter.database

import org.springframework.context.annotation.Configuration
import org.springframework.data.mongodb.repository.config.EnableReactiveMongoRepositories

@Configuration
@EnableReactiveMongoRepositories
class DatabaseConfiguration
