name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branche
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@master
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build & Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -U -P coverage clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Release & Publish
        run: mvn -B --settings settings.xml -Darguments=-DskipTests release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout tag
        run: git checkout $(git describe --abbrev=0 --tags)

      - name: Build Docker
        run: mvn -B spring-boot:build-image -Dspring-boot.build-image.imageName=deroffal/mesrecettes-back

      - name: Push to DockerHub
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker tag deroffal/mesrecettes-back:latest deroffal/mesrecettes-back:${VERSION}
          docker push deroffal/mesrecettes-back:${VERSION}
          docker push deroffal/mesrecettes-back:latest
